services:

  db:
    container_name: mysql_db
    image: mysql:latest
    #restart: always
        
    env_file:
     - ./.env
    volumes:
    - mysql_data:/var/lib/mysql
    #- ./db-init-scripts:/docker-entrypoint-initdb.d

    ports:
     - "3306:3306"
    

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3


  web:
    container_name: django_web
    build: 
      context: ./backend
      dockerfile: .devcontainer/Dockerfile

    env_file:
     - ./.env
    volumes:
     - ./backend:/app

    ports:
     - "8000:8000"

    working_dir: /app
    command: bash ss.sh

    depends_on:
      db:
        condition: service_healthy


  frontend:
    container_name: svelte_frontend
    build:
      context: ./frontend
      dockerfile: .devcontainer/Dockerfile

    env_file:
     - ./.env
    volumes: 
     - ./frontend:/app
    
    ports:
     - "5173:5173"

    working_dir: /app
    command: bash ss.sh



volumes: 
  mysql_data:
  #mounted persistant data folder /var/lib/mysql into this docker volume