services:
<<<<<<< Updated upstream
#try fork 1
=======
>>>>>>> Stashed changes
  db:
    container_name: mysql_db
    image: mysql:8.0
    
    #restart: always
        
    env_file:
     - ./.env
    volumes:
    - mysql_data:/var/lib/mysql
    #- ./db-init-scripts:/docker-entrypoint-initdb.d

    ports:
     - "3306:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s


  backend:
    container_name: django_backend
    build: 
      context: ./backend
      dockerfile: .devcontainer/Dockerfile

    env_file:
     - ./.env
    volumes:
     - ./backend:/app

    ports:
     - "8000:8000"

    working_dir: /app
    command: bash ss.sh

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3

    depends_on:
      db:
        condition: service_healthy


  frontend:
    container_name: svelte_frontend
    build:
      context: ./frontend
      dockerfile: .devcontainer/Dockerfile

    env_file:
     - ./.env
    volumes: 
     - ./frontend:/app
    
    ports:
     - "5173:5173"

    working_dir: /app
    command: bash ss.sh

    depends_on:
      - "backend"


volumes: 
  mysql_data:
