services:


  web:
    container_name: django_web
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
     - "8000:8000"
    volumes:
     - ..:/app
    working_dir: /app/learn
    command: python manage.py runserver 0.0.0.0:8000

  db:
    container_name: sqlite_db
    image: nouchka/sqlite3:latest
    volumes:
     - sqlite_data:/sqlite_data


volumes:
  sqlite_data: