services:


  db:
    container_name: mysql_db
    image: mysql:latest
    #restart: always
        
    env_file:
     - ../config/.env
    volumes:
    - mysql_data:/var/lib/mysql
    #- ./db-init-scripts:/docker-entrypoint-initdb.d

    ports:
     - "3306:3306"
    

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3



  web:
    container_name: django_web
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile

    env_file:
     - ../config/.env
    volumes:
     - ..:/app

    ports:
     - "8000:8000"

    depends_on:
      - db

    working_dir: /app/learn
    #command: python manage.py runserver 0.0.0.0:8000
    #command: bash config/ss.sh
    command: bash

  

volumes: 
  mysql_data:
  #mounted persistant data folder /var/lib/mysql into this docker volume