services:


  web:
    container_name: django_web
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
     - ../config/.env
    ports:
     - "8000:8000"
    volumes:
     - ..:/app
    depends_on:
      - db

    working_dir: /app/learn
    #command: python manage.py runserver 0.0.0.0:8000
    #command: bash config/ss.sh
    command: bash

  db:
    container_name: mysql_db
    image: mysql:latest
    #restart: always
        
    env_file:
     - ../config/.env
  # Set the root password

    ports:
     - "3306:3306"
    volumes:
    - mysql_data:/var/lib/mysql
    #- ./init.sql:/docker-entrypoint-initdb.d/init.sql

    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

     
    #command: --authentication-policy=mysql_native_password



volumes: 
  mysql_data:
  #mounted persistant data folder /var/lib/mysql into this docker volume