# Generated by Django 5.1.5 on 2025-01-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_game_team_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='games_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
