# Generated by Django 5.1.5 on 2025-02-12 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_player_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='firstapp.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='firstapp.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AtBat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.PositiveIntegerField()),
                ('strikes', models.PositiveIntegerField(default=0)),
                ('outcome', models.CharField(choices=[('OUT_3', '3 Strikes and Out'), ('OUT_2', '2 Strikes and Out'), ('OUT_1', '1 Strike and Out'), ('OUT_0', '0 Strikes and Out'), ('SINGLE', 'Single (1 Base Hit)'), ('DOUBLE', 'Double (2 Base Hits)'), ('TRIPLE', 'Triple (3 Base Hits)'), ('HOMERUN', 'Home Run')], max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_bats', to='firstapp.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_bats', to='firstapp.player')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.PositiveIntegerField(default=0)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('rbis', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='firstapp.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='firstapp.player')),
            ],
        ),
    ]
