# Generated by Django 5.1.6 on 2025-02-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_game_away_team_game_away_team_score_game_home_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
