# Generated by Django 5.1.6 on 2025-02-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_team_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
    ]
